import Footer from '../components/Navigation/Footer';
import Logo from '../components/Navigation/Logo';
import Menu from '../components/Navigation/Menu';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <div>
      <Menu color="text-white" isLandingPage={true} />
      <Logo />
      {children}
      <Footer />
    </div>
  );
}
