import './globals.css';

import { Inter } from 'next/font/google';

import Footer from './components/Navigation/Footer';
import Logo from './components/Navigation/Logo';
import Menu from './components/Navigation/Menu';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
  searchParams: any;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
